### ISSUE TITLE
PROTOCOL_TIMEOUT Errors on some urls

### ISSUE THREAD

**Issue by sebasrodriguez** [foo-software/lighthouse-check#10]
Hey guys, first of all, great project. I've integrated it pretty easily on circleci. 

I'm having trouble running it against some urls, it's giving me a timeout error:

```
- lighthouse-check: Running...

❌  Something went wrong while attempting to enqueue URLs for Lighthouse. See the error below.

 { LHError: PROTOCOL_TIMEOUT
    at Timeout.setTimeout [as _onTimeout] (/usr/local/lib/node_modules/@foo-software/lighthouse-check/node_modules/lighthouse/lighthouse-core/gather/driver.js:409:21)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
  name: 'LHError',
  code: 'PROTOCOL_TIMEOUT',
  friendlyMessage:
   'Waiting for DevTools protocol response has exceeded the allotted time. (Method: Emulation.setScriptExecutionDisabled)',
  lhrRuntimeError: true,
  protocolMethod: 'Emulation.setScriptExecutionDisabled' }
```

The weird part is that this only happens when I'm running it on circleci or a docker container but not when I execute it using the lighthouse-check cli command from my local computer. 

One of the urls I'm having trouble is: https://www.ourbranch.com

**Comment by adamhenson** [comment]
Thanks for reporting this @sebasrodriguez. My questions:

- Could you provide your config?
- With the same config, is the issue occurring only for certain URLs?
- For those URLs do the errors occur consistently or is it intermittent?

I successfully ran an audit on https://www.ourbranch.com via Automated Lighthouse Check which runs within a Docker container [seen here](https://www.automated-lighthouse-check.com/dashboard/page/5e68f3d1b7d19000246a31ed).

`PROTOCOL_TIMEOUT` is a common error that I've seen for a variety of reasons, but we'll get to the bottom of it.

**Comment by sebasrodriguez** [comment]
Hi @adamhenson. 

I'll paste you a minimal config that fails consistently when I run it against https://www.ourbranch.com

```
version: 2.1

orbs:
  lighthouse-check: foo-software/lighthouse-check@0.0.8

jobs:
  lighthouse:
    executor: lighthouse-check/default
    steps:
      - lighthouse-check/audit:
          urls: https://www.ourbranch.com
workflows:
  version: 2
  build:
    jobs:
      - lighthouse
```

You'll need to have installed circleci locally installed and then run:
- `circleci config process .circleci/config.yml > process.yml`
- `circleci local execute -c process.yml --job lighthouse`

I've tried it with a few urls under ourbranch.com and it also fails with the same error.
