### ISSUE TITLE
Passing custom lighthouse options to lighthouse-persist

### ISSUE THREAD

**Issue by gslama-akqa** [foo-software/lighthouse-check#23]
I am currently in process ligthouse-check as Github Actions for a project hosted on Netlify.

It's working smoothly apart from one thing. I need to be able to pass a custom option (disableStorageReset) to ligthouse to be able to implement this [recipe](https://github.com/GoogleChrome/lighthouse/blob/master/docs/recipes/auth/example-lh-auth.js#L66).

I can see this is already handled at the [ligthouse-persist](https://github.com/foo-software/lighthouse-persist/blob/master/src/index.js#L16) level but there's apparently no way to pass such data from lighthouse-check-action to lighthouse-persist.

Would it make sense to pass this as an option? If so I'd happily create a PR.

Thanks!

**Comment by adamhenson** [comment]
Hi @gslama-akqa - thanks for raising this issue. This is a valid issue that is the highest priority at the moment. I believe we should have a solution in the next couple weeks. It's also captured in the [`lighthouse-check-action` project in issue #12](https://github.com/foo-software/lighthouse-check-action/issues/12). Let's keep this open too. I'm imagining a custom config file.

**Comment by gslama-akqa** [comment]
Hi Adam, that's great news.

Thanks a lot for your project that is of great help for our team!

**Comment by adamhenson** [comment]
@gslama-akqa - support for this is now available in both [`@foo-software/lighthouse-check@0.0.86`](https://www.npmjs.com/package/@foo-software/lighthouse-check) and in [`lighthouse-check-action@1.0.11`](https://github.com/foo-software/lighthouse-check-action/releases/tag/v1.0.11). If you're using the GitHub action you can specify `overridesJsonFile` as [explained here](https://github.com/foo-software/lighthouse-check-action#usage-overriding-config-and-option-defaults).

Perhaps something like:

> .github/workflows/test.yml

```yaml
name: Test
on: [push]

jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Lighthouse
      uses: foo-software/lighthouse-check-action@master
      with:
        overridesJsonFile: 'overrides.json'
        urls: 'https://www.foo.software'
```

> overrides.json

```json
{
  "options": {
    "disableStorageReset": true
  }
}
```

Thanks for reporting this. Please let me know how this goes. Closing this unless any related issues come up.
