### ISSUE TITLE
Lighthouse performance result 0

### ISSUE THREAD

**Issue by robert-kmieciak-vmltech** [foo-software/lighthouse-check#52]
Hi there, 
I am getting `performance` result `0` while running Lighthouse Check - and have no idea why. Any ide what I am missing? 

My pipeline configuration: 
```
   - name: Run Lighthouse
        uses: foo-software/lighthouse-check-action@master
        id: lighthouseCheck
        with:
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          urls: '${{ steps.get_project_url.outputs.prop }}'
          prCommentEnabled: true
          prCommentSaveOld: false
          throttling: 'mobileSlow4G'
          emulatedFormFactor: 'mobile'`

      - name: Handle Lighthouse Check results
        uses: foo-software/lighthouse-check-status-action@master
        with:
          lighthouseCheckResults: ${{ steps.lighthouseCheck.outputs.lighthouseCheckResults }}
          minAccessibilityScore: "80"
          minBestPracticesScore: "80"
          minPerformanceScore: "0"
          minProgressiveWebAppScore: "60"
          minSeoScore: "80"
```

GH Actions logs display this 
![image](https://user-images.githubusercontent.com/81171488/126333522-dcd7256e-5ef8-4c16-be2f-7bcbbca8d323.png)
