### ISSUE TITLE
PWA check returns wrong value

### ISSUE THREAD

**Issue by amokato** [foo-software/lighthouse-check#55]
Our website does not use PWA but the Lighthouse score always returns 42. I don't know if 42 is an easter egg ;) but I would prefer a 0 or n. a. My implementation looks like this (in the jobs section):

```
lighthouse-check-desktop:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [safari-job, chrome-job, firefox-job]
    steps:
      - uses: actions/checkout@master
      - run: mkdir /tmp/artifacts
      - name: Run Lighthouse Desktop
        uses: foo-software/lighthouse-check-action@master
        id: lighthouseCheck
        with:
          device: "desktop"
          maxRetries: 3
          gitAuthor: ${{ github.actor }}
          gitBranch: ${{ github.ref }}
          outputDirectory: /tmp/artifacts
          urls: ${{ secrets.STAGE_URL }}
          sha: ${{ github.sha }}
          slackWebhookUrl: ${{ secrets.SLACK_WEBHOOK }}
```
![Bildschirmfoto 2021-11-12 um 09 29 03](https://user-images.githubusercontent.com/53219214/141435403-4a6dd354-e9d9-49c8-9644-9f171c92e085.png)
